import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio Iker Navas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body
        className={`bg-background text-foreground min-h-screen flex flex-col relative ${geistSans.variable} ${geistMono.variable}`}
      >
        <div id="app-content" className="flex flex-col min-h-screen">
          <Header />
          <div className="flex-1 w-full flex justify-center">
            <div className="w-full max-w-6xl bg-[#393C42] rounded-xl p-6 md:p-10 shadow-lg">
              {children}
            </div>
          </div>
          <Footer />
        </div>

        {/* Nodo para el portal del modal */}
        <div id="modal-root"></div>

        {/* Notificaciones globales */}
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
